# Generated by Django 4.2 on 2023-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('IN', 'Infra'), ('DE', 'Desenvolvimento'), ('DG', 'Design'), ('PL', 'Planejamento'), ('BD', 'Banco de Dados')], max_length=4, null=True),
        ),
    ]
