# Generated by Django 4.2 on 2023-04-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('INFRA', 'Infra'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('DESIGN', 'Design'), ('PLANEJAMENTO', 'Planejamento'), ('BANCO_DADOS', 'Banco de Dados')], max_length=15, null=True),
        ),
    ]
