# Generated by Django 4.2 on 2023-04-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Infra', 'Infra'), ('Desenvolvimento', 'Desenvolvimento'), ('Design', 'Design'), ('Planejamento', 'Planejamento'), ('Banco de Dados', 'Banco de Dados')], max_length=15, null=True),
        ),
    ]
