# Generated by Django 4.2 on 2023-05-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_alter_project_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='card',
            field=models.CharField(default=[], max_length=60),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
