# Generated by Django 4.2 on 2023-05-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_service_alter_project_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
    ]
