# Generated by Django 4.2 on 2023-05-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_project_service_project_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='card',
        ),
        migrations.AddField(
            model_name='project',
            name='card',
            field=models.ManyToManyField(blank=True, null=True, to='api.card'),
        ),
    ]
