# Generated by Django 4.2 on 2023-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_project_category_category_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='card',
            field=models.ManyToManyField(blank=True, to='api.card'),
        ),
    ]
