# Generated by Django 4.2 on 2023-05-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_category_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='card',
            field=models.ManyToManyField(blank=True, null=True, to='api.card'),
        ),
    ]
